import argparse
import os

import pandas as pd


# Base directory containing one result directory per membrane image.
parser = argparse.ArgumentParser(description="Summarize per-membrane processing times.")
parser.add_argument("--base-dir", required=True, help="Directory containing per-image result folders.")
base_dir = parser.parse_args().base_dir

results = []

# Read the timing table from every per-image result directory.
for folder in os.listdir(base_dir):
    sub_path = os.path.join(base_dir, folder, "timing_statistics.csv")
    if os.path.exists(sub_path):
        try:
            # Read the two-column CSV generated by APP5.0.py.
            df = pd.read_csv(sub_path)
            if "Metric" in df.columns and "Value" in df.columns:
                value = df.loc[df["Metric"] == "Total image processing time (s)", "Value"]
                if not value.empty:
                    results.append(
                        {
                            "Sample name": folder,
                            "Total image processing time (s)": float(value.iloc[0]),
                        }
                    )
        except Exception as error:
            print(f"Error reading {sub_path}: {error}")

# Summarize all valid per-image timing records.
summary_df = pd.DataFrame(results)

if not summary_df.empty:
    avg_time = summary_df["Total image processing time (s)"].mean()
    print("Total image processing time by sample:")
    print(summary_df)
    print(f"\nMean total image processing time (s): {avg_time:.2f}")

    # Save the combined timing table.
    output_path = os.path.join(base_dir, "processing_time_summary.csv")
    summary_df.to_csv(output_path, index=False, encoding="utf-8-sig")
    print(f"\nSaved the summary to: {output_path}")
else:
    print("No valid timing_statistics.csv files were found, or their format did not match.")
